# Generated by Django 4.1.7 on 2023-03-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="classes",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="school",
            fields=[
                ("school_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("address", models.TextField()),
                ("mail", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=13)),
                ("created_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="section",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subject",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="students",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=250)),
                ("age", models.IntegerField()),
                ("address", models.TextField()),
                ("dob", models.DateField()),
                ("phone_number", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=254)),
                ("joining_date", models.DateField(auto_now=True)),
                (
                    "classes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.classes",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.school",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.section",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="staffs",
            fields=[
                (
                    "staff_id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("classes", models.CharField(max_length=250)),
                ("section", models.CharField(max_length=250)),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=250)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=13)),
                ("joining_date", models.DateField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.BigIntegerField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="login_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=150)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.school",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.staffs",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_app.students",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classes",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="management_app.school"
            ),
        ),
    ]
